using OpenScrape.App.Helpers;

namespace OpenScrape.App.Tables
{
    public static class OpenRaiseVs3Bet
    {
        public static string GetOpenRaiseSBvs3BetBB(string hand)
        {
            return OpenRaiseSBvs3BetBB(hand);
        }

        public static string GetOpenRaiseBTNvs3BetBB(string hand)
        {
            return OpenRaiseBTNvs3BetBB(hand);
        }

        public static string GetOpenRaiseBTNvs3BetSB(string hand)
        {
            return OpenRaiseBTNvs3BetSB(hand);
        }

        public static string GetOpenRaiseCOvs3BetBB(string hand)
        {
            return OpenRaiseCOvs3BetBB(hand);
        }

        public static string GetOpenRaiseCOvs3BetSB(string hand)
        {
            return OpenRaiseCOvs3BetSB(hand);
        }

        public static string GetOpenRaiseCOvs3BetBTN(string hand)
        {
            return OpenRaiseCOvs3BetBTN(hand);
        }

        public static string GetOpenRaiseMPvs3BetBB(string hand)
        {
            return OpenRaiseMPvs3BetBB(hand);
        }

        public static string GetOpenRaiseMPvs3BetSB(string hand)
        {
            return OpenRaiseMPvs3BetSB(hand);
        }

        public static string GetOpenRaiseMPvs3BetBTN(string hand)
        {
            return OpenRaiseMPvs3BetBTN(hand);
        }

        public static string GetOpenRaiseMPvs3BetCO(string hand)
        {
            return OpenRaiseMPvs3BetCO(hand);
        }

        public static string GetOpenRaiseEPvs3BetBB(string hand)
        {
            return OpenRaiseEPvs3BetBB(hand);
        }

        public static string GetOpenRaiseEPvs3BetSB(string hand)
        {
            return OpenRaiseEPvs3BetSB(hand);
        }

        public static string GetOpenRaiseEPvs3BetBTN(string hand)
        {
            return OpenRaiseEPvs3BetBTN(hand);
        }

        public static string GetOpenRaiseEPvs3BetCO(string hand)
        {
            return OpenRaiseEPvs3BetCO(hand);
        }

        #region Hands

        private static string OpenRaiseSBvs3BetBB(string hand)
        {
            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "A9s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "A9s", Action = "Call", Porcentajes = 51 },
                new Hands { Hand = "A8s", Action = "4Bet x20", Porcentajes = 15 },
                new Hands { Hand = "A8s", Action = "Call", Porcentajes = 85 },
                new Hands { Hand = "A7s", Action = "4Bet x20", Porcentajes = 10 },
                new Hands { Hand = "A7s", Action = "Call", Porcentajes = 90 },
                new Hands { Hand = "A6s", Action = "4Bet x20", Porcentajes = 60 },
                new Hands { Hand = "A6s", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "A5s", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "A5s", Action = "Call", Porcentajes = 80 },
                new Hands { Hand = "A4s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "A4s", Action = "Call", Porcentajes = 51 },
                new Hands { Hand = "A3s", Action = "4Bet x20", Porcentajes = 60 },
                new Hands { Hand = "A3s", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "A2s", Action = "4Bet x20", Porcentajes = 30 },
                new Hands { Hand = "A2s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 10 },
                new Hands { Hand = "AKo", Action = "4Bet x20", Porcentajes = 90 },
                new Hands { Hand = "KK", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "All-In", Porcentajes = 40 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "K9s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "K9s", Action = "Call", Porcentajes = 51 },
                new Hands { Hand = "K8s", Action = "Fold", Porcentajes = 20 },
                new Hands { Hand = "K8s", Action = "4Bet x20", Porcentajes = 30 },
                new Hands { Hand = "K8s", Action = "Marginal Call", Porcentajes = 50 },
                new Hands { Hand = "K7s", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "K7s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "K5s", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 10 },
                new Hands { Hand = "AQo", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "AQo", Action = "All-In", Porcentajes = 70 },
                new Hands { Hand = "KQo", Action = "Call", Porcentajes = 30 },
                new Hands { Hand = "KQo", Action = "4Bet x20", Porcentajes = 70 },
                new Hands { Hand = "QQ", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "QTs", Action = "4Bet x20", Porcentajes = 10 },
                new Hands { Hand = "QTs", Action = "Call", Porcentajes = 90 },
                new Hands { Hand = "Q9s", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "Q9s", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "AJo", Action = "Call", Porcentajes = 5 },
                new Hands { Hand = "AJo", Action = "4Bet x20", Porcentajes = 95 },
                new Hands { Hand = "KJo", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "KJo", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "KJo", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "QJo", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "QJo", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "JJ", Action = "4Bet x20", Porcentajes = 100 },
                new Hands { Hand = "JTs", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "JTs", Action = "Call", Porcentajes = 80 },
                new Hands { Hand = "J9s", Action = "Call", Porcentajes = 45 },
                new Hands { Hand = "J9s", Action = "4Bet x20", Porcentajes = 55 },
                new Hands { Hand = "J8s", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "J8s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "ATo", Action = "Fold", Porcentajes = 20 },
                new Hands { Hand = "ATo", Action = "4Bet x20", Porcentajes = 80 },
                new Hands { Hand = "KTo", Action = "4Bet x20", Porcentajes = 20 },
                new Hands { Hand = "KTo", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "QTo", Action = "4Bet x20", Porcentajes = 10 },
                new Hands { Hand = "QTo", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "TT", Action = "All-In", Porcentajes = 30 },
                new Hands { Hand = "TT", Action = "4Bet x20", Porcentajes = 70 },
                new Hands { Hand = "T9s", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "T9s", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "T8s", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "T8s", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "T8s", Action = "4Bet x20", Porcentajes = 50 },
                new Hands { Hand = "99", Action = "All-In", Porcentajes = 10 },
                new Hands { Hand = "99", Action = "4Bet x20", Porcentajes = 30 },
                new Hands { Hand = "99", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "98s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "97s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "97s", Action = "4Bet x20", Porcentajes = 60 },
                new Hands { Hand = "88", Action = "All-In", Porcentajes = 10 },
                new Hands { Hand = "88", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "88", Action = "Call", Porcentajes = 50 },
                new Hands { Hand = "87s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "86s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "86s", Action = "4Bet x20", Porcentajes = 60 },
                new Hands { Hand = "77", Action = "All-In", Porcentajes = 20 },
                new Hands { Hand = "77", Action = "4Bet x20", Porcentajes = 39 },
                new Hands { Hand = "77", Action = "Call", Porcentajes = 41 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "76s", Action = "4Bet x20", Porcentajes = 60 },
                new Hands { Hand = "66", Action = "All-In", Porcentajes = 29 },
                new Hands { Hand = "66", Action = "Call", Porcentajes = 31 },
                new Hands { Hand = "66", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "65s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "55", Action = "All-In", Porcentajes = 20 },
                new Hands { Hand = "55", Action = "4Bet x20", Porcentajes = 30 },
                new Hands { Hand = "55", Action = "Call", Porcentajes = 50 },
                new Hands { Hand = "54s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "44", Action = "All-In", Porcentajes = 29 },
                new Hands { Hand = "44", Action = "Call", Porcentajes = 31 },
                new Hands { Hand = "44", Action = "4Bet x20", Porcentajes = 40 },
                new Hands { Hand = "43s", Action = "4Bet x20", Porcentajes = 49 },
                new Hands { Hand = "43s", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "33", Action = "4Bet x20", Porcentajes = 29 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 31 },
                new Hands { Hand = "33", Action = "All-In", Porcentajes = 40 },
                new Hands { Hand = "22", Action = "4Bet x20", Porcentajes = 29 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 31 },
                new Hands { Hand = "22", Action = "All-In", Porcentajes = 40 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseBTNvs3BetBB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "4Bet x23.5", Porcentajes = 49 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 51 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "A9s", Action = "4Bet x23.5", Porcentajes = 10 },
                new Hands { Hand = "A9s", Action = "Call", Porcentajes = 90 },
                new Hands { Hand = "A8s", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "A8s", Action = "Call", Porcentajes = 70 },
                new Hands { Hand = "A7s", Action = "4Bet x23.5", Porcentajes = 60 },
                new Hands { Hand = "A7s", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "A6s", Action = "4Bet x23.5", Porcentajes = 40 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "A5s", Action = "All-In", Porcentajes = 20 },
                new Hands { Hand = "A5s", Action = "4Bet x23.5", Porcentajes = 25 },
                new Hands { Hand = "A5s", Action = "Call", Porcentajes = 55 },
                new Hands { Hand = "A4s", Action = "4Bet x23.5", Porcentajes = 50 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 20 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 25 },
                new Hands { Hand = "AKo", Action = "4Bet x23.5", Porcentajes = 75 },
                new Hands { Hand = "KK", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "K9s", Action = "4Bet x23.5", Porcentajes = 20 },
                new Hands { Hand = "K9s", Action = "Call", Porcentajes = 80 },
                new Hands { Hand = "K8s", Action = "4Bet x23.5", Porcentajes = 10 },
                new Hands { Hand = "K8s", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "K8s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "K5s", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "AQo", Action = "All-In", Porcentajes = 50 },
                new Hands { Hand = "AQo", Action = "4Bet x23.5", Porcentajes = 20 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 30 },
                new Hands { Hand = "KQo", Action = "4Bet x23.5", Porcentajes = 60 },
                new Hands { Hand = "KQo", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "KQo", Action = "Fold", Porcentajes = 10 },
                new Hands { Hand = "QQ", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "QTs", Action = "4Bet x23.5", Porcentajes = 35 },
                new Hands { Hand = "QTs", Action = "Call", Porcentajes = 65 },
                new Hands { Hand = "Q9s", Action = "4Bet x23.5", Porcentajes = 25 },
                new Hands { Hand = "Q9s", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "Q8s", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "Q8s", Action = "Fold", Porcentajes = 95 },
                new Hands { Hand = "AJo", Action = "4Bet x23.5", Porcentajes = 60 },
                new Hands { Hand = "AJo", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "AJo", Action = "Fold", Porcentajes = 20 },
                new Hands { Hand = "JJ", Action = "All-In", Porcentajes = 20 },
                new Hands { Hand = "JJ", Action = "4Bet x23.5", Porcentajes = 70 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 10 },
                new Hands { Hand = "JTs", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "JTs", Action = "Call", Porcentajes = 95 },
                new Hands { Hand = "ATo", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "ATo", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "TT", Action = "All-In", Porcentajes = 15 },
                new Hands { Hand = "TT", Action = "4Bet x23.5", Porcentajes = 25 },
                new Hands { Hand = "TT", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "T9s", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "99", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "99", Action = "Call", Porcentajes = 95 },
                new Hands { Hand = "88", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "88", Action = "Call", Porcentajes = 70 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "77", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 55 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 60 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "55", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "54s", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "33", Action = "4Bet x23.5", Porcentajes = 5 },
                new Hands { Hand = "33", Action = "Fold", Porcentajes = 95 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseBTNvs3BetSB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "4Bet x23.5", Porcentajes = 48 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 52 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "A9s", Action = "4Bet x23.5", Porcentajes = 56 },
                new Hands { Hand = "A9s", Action = "Call", Porcentajes = 44 },                
                new Hands { Hand = "A8s", Action = "4Bet x23.5", Porcentajes = 56 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 44 },
                new Hands { Hand = "A7s", Action = "4Bet x23.5", Porcentajes = 45 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "A6s", Action = "4Bet x23.5", Porcentajes = 74 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 26 },
                new Hands { Hand = "A5s", Action = "4Bet x23.5", Porcentajes = 15 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 31 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 54 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 3 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 97 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 2 },
                new Hands { Hand = "AKo", Action = "4Bet x23.5", Porcentajes = 98 },
                new Hands { Hand = "KK", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KTs", Action = "4Bet x23.5", Porcentajes = 9 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 91 },
                new Hands { Hand = "K9s", Action = "4Bet x23.5", Porcentajes = 11 },
                new Hands { Hand = "K9s", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 74 },
                new Hands { Hand = "AQo", Action = "All-In", Porcentajes = 43 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 57 },
                new Hands { Hand = "KQo", Action = "4Bet x23.5", Porcentajes = 77 },
                new Hands { Hand = "KQo", Action = "Marginal Call", Porcentajes = 13 },
                new Hands { Hand = "KQo", Action = "Fold", Porcentajes = 10 },
                new Hands { Hand = "QQ", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "4Bet x23.5", Porcentajes = 37 },
                new Hands { Hand = "QJs", Action = "Call", Porcentajes = 63 },
                new Hands { Hand = "QTs", Action = "4Bet x23.5", Porcentajes = 83 },
                new Hands { Hand = "QTs", Action = "Call", Porcentajes = 17 },
                new Hands { Hand = "Q9s", Action = "4Bet x23.5", Porcentajes = 31 },
                new Hands { Hand = "Q9s", Action = "Fold", Porcentajes = 69 },
                new Hands { Hand = "AJo", Action = "4Bet x23.5", Porcentajes = 63 },
                new Hands { Hand = "AJo", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "AJo", Action = "Fold", Porcentajes = 20 },
                new Hands { Hand = "JJ", Action = "4Bet x23.5", Porcentajes = 100 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 52 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 48 },
                new Hands { Hand = "ATo", Action = "4Bet x23.5", Porcentajes = 13 },
                new Hands { Hand = "ATo", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "TT", Action = "4Bet x23.5", Porcentajes = 79 },
                new Hands { Hand = "TT", Action = "Call", Porcentajes = 21 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "99", Action = "All-In", Porcentajes = 30 },
                new Hands { Hand = "99", Action = "4Bet x23.5", Porcentajes = 7 },
                new Hands { Hand = "99", Action = "Call", Porcentajes = 63 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 39 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 61 },
                new Hands { Hand = "88", Action = "4Bet x23.5", Porcentajes = 30 },
                new Hands { Hand = "88", Action = "Call", Porcentajes = 70 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 22 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "77", Action = "4Bet x23.5", Porcentajes = 15 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 54 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 31 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "66", Action = "4Bet x23.5", Porcentajes = 4 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 37 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 59 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "55", Action = "4Bet x23.5", Porcentajes = 10 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "54s", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "33", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "33", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "22", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "22", Action = "Fold", Porcentajes = 85 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseCOvs3BetBB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x22.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x22.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "4Bet x22.5", Porcentajes = 32 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 68 },
                new Hands { Hand = "A9s", Action = "4Bet x22.5", Porcentajes = 20 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 10 },
                new Hands { Hand = "A8s", Action = "4Bet x22.5", Porcentajes = 75 },
                new Hands { Hand = "A8s", Action = "Call", Porcentajes = 25 },
                new Hands { Hand = "A7s", Action = "4Bet x22.5", Porcentajes = 46 },
                new Hands { Hand = "A7s", Action = "Marginal Call", Porcentajes = 6 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 48 },
                new Hands { Hand = "A6s", Action = "4Bet x22.5", Porcentajes = 8 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 92 },
                new Hands { Hand = "A5s", Action = "4Bet x22.5", Porcentajes = 10 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 73 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 17 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 10 },
                new Hands { Hand = "AKo", Action = "4Bet x22.5", Porcentajes = 50 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "KK", Action = "4Bet x22.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "4Bet x22.5", Porcentajes = 15 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 85 },
                new Hands { Hand = "KTs", Action = "4Bet x22.5", Porcentajes = 42 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 58 },
                new Hands { Hand = "K9s", Action = "4Bet x22.5", Porcentajes = 30 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "K8s", Action = "4Bet x22.5", Porcentajes = 15 },
                new Hands { Hand = "K8s", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "K5s", Action = "4Bet x22.5", Porcentajes = 20 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "K4s", Action = "4Bet x22.5", Porcentajes = 8 },
                new Hands { Hand = "K4s", Action = "Fold", Porcentajes = 92 },
                new Hands { Hand = "AQo", Action = "4Bet x22.5", Porcentajes = 77 },
                new Hands { Hand = "AQo", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "QQ", Action = "4Bet x22.5", Porcentajes = 59 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 41 },
                new Hands { Hand = "QJs", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "QJs", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 47 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 53 },
                new Hands { Hand = "AJo", Action = "4Bet x22.5", Porcentajes = 4 },
                new Hands { Hand = "AJo", Action = "Fold", Porcentajes = 96 },
                new Hands { Hand = "KJo", Action = "4Bet x22.5", Porcentajes = 12 },
                new Hands { Hand = "KJo", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "JJ", Action = "4Bet x22.5", Porcentajes = 20 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 80 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 4 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 96 },
                new Hands { Hand = "TT", Action = "4Bet x22.5", Porcentajes = 2 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 82 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 16 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 45 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 42 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 58 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 26 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 74 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 37 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 63 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 54 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 46 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "54s", Action = "Marginal Call", Porcentajes = 85 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 4 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 96 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseCOvs3BetSB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "4Bet x22", Porcentajes = 75 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 25 },
                new Hands { Hand = "A8s", Action = "4Bet x22", Porcentajes = 51 },
                new Hands { Hand = "A8s", Action = "Call", Porcentajes = 49 },
                new Hands { Hand = "A7s", Action = "4Bet x22", Porcentajes = 47 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 53 },
                new Hands { Hand = "A6s", Action = "4Bet x22", Porcentajes = 44 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 56 },
                new Hands { Hand = "A5s", Action = "4Bet x22", Porcentajes = 4 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 14 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "AKo", Action = "4Bet x22", Porcentajes = 70 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 30 },
                new Hands { Hand = "KK", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "4Bet x22", Porcentajes = 75 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 25 },
                new Hands { Hand = "KTs", Action = "4Bet x22", Porcentajes = 65 },
                new Hands { Hand = "KTs", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 18 },
                new Hands { Hand = "K9s", Action = "4Bet x22", Porcentajes = 25 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "K5s", Action = "4Bet x22", Porcentajes = 60 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "K4s", Action = "4Bet x22", Porcentajes = 20 },
                new Hands { Hand = "K4s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "AQo", Action = "4Bet x22", Porcentajes = 92 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 8 },
                new Hands { Hand = "KQo", Action = "4Bet x22", Porcentajes = 8 },
                new Hands { Hand = "KQo", Action = "Fold", Porcentajes = 92 },
                new Hands { Hand = "QQ", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "QJs", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 14 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 86 },
                new Hands { Hand = "AJo", Action = "4Bet x22", Porcentajes = 12 },
                new Hands { Hand = "AJo", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "JJ", Action = "4Bet x22", Porcentajes = 62 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 38 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 24 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 76 },
                new Hands { Hand = "TT", Action = "4Bet x22", Porcentajes = 42 },
                new Hands { Hand = "TT", Action = "Call", Porcentajes = 58 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "4Bet x22", Porcentajes = 2 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 41 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "88", Action = "4Bet x22", Porcentajes = 2 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 28 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 26 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 74 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 62 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 92 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "33", Action = "Marginal Call", Porcentajes = 32 },
                new Hands { Hand = "33", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "22", Action = "Marginal Call", Porcentajes = 49 },
                new Hands { Hand = "22", Action = "Fold", Porcentajes = 51 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseCOvs3BetBTN(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x21.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x21.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "ATs", Action = "4Bet x21.5", Porcentajes = 66 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 34 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 13 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "A8s", Action = "4Bet x21.5", Porcentajes = 29 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 5 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 66 },
                new Hands { Hand = "A7s", Action = "4Bet x21.5", Porcentajes = 53 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 47 },
                new Hands { Hand = "A6s", Action = "4Bet x21.5", Porcentajes = 30 },
                new Hands { Hand = "A6s", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 45 },
                new Hands { Hand = "A5s", Action = "4Bet x21.5", Porcentajes = 34 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 54 },
                new Hands { Hand = "AKo", Action = "4Bet x21.5", Porcentajes = 97 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 3 },
                new Hands { Hand = "KK", Action = "4Bet x21.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "4Bet x21.5", Porcentajes = 10 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 90 },
                new Hands { Hand = "KJs", Action = "4Bet x21.5", Porcentajes = 76 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 24 },
                new Hands { Hand = "KTs", Action = "4Bet x21.5", Porcentajes = 85 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 15 },
                new Hands { Hand = "K9s", Action = "4Bet x21.5", Porcentajes = 37 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 63 },
                new Hands { Hand = "K7s", Action = "4Bet x21.5", Porcentajes = 13 },
                new Hands { Hand = "K7s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "K6s", Action = "4Bet x21.5", Porcentajes = 15 },
                new Hands { Hand = "K6s", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "K5s", Action = "4Bet x21.5", Porcentajes = 40 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "K4s", Action = "4Bet x21.5", Porcentajes = 6 },
                new Hands { Hand = "K4s", Action = "Fold", Porcentajes = 94 },
                new Hands { Hand = "AQo", Action = "4Bet x21.5", Porcentajes = 97 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 3 },
                new Hands { Hand = "KQo", Action = "4Bet x21.5", Porcentajes = 33 },
                new Hands { Hand = "KQo", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "QQ", Action = "4Bet x21.5", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "4Bet x21.5", Porcentajes = 15 },
                new Hands { Hand = "QJs", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "QJs", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "AJo", Action = "4Bet x21.5", Porcentajes = 32 },
                new Hands { Hand = "AJo", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "JJ", Action = "4Bet x21.5", Porcentajes = 96 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 4 },
                new Hands { Hand = "JTs", Action = "4Bet x21.5", Porcentajes = 29 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 21 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "TT", Action = "4Bet x21.5", Porcentajes = 55 },
                new Hands { Hand = "TT", Action = "Call", Porcentajes = 45 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "4Bet x21.5", Porcentajes = 45 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 53 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 2 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "97s", Action = "Marginal Call", Porcentajes = 4 },
                new Hands { Hand = "97s", Action = "Fold", Porcentajes = 96 },
                new Hands { Hand = "88", Action = "4Bet x21.5", Porcentajes = 19 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 41 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "86s", Action = "Marginal Call", Porcentajes = 4 },
                new Hands { Hand = "86s", Action = "Fold", Porcentajes = 96 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 34 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 66 },
                new Hands { Hand = "65s", Action = "4Bet x21.5", Porcentajes = 48 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 19 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 21 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 79 },
                new Hands { Hand = "54s", Action = "4Bet x21.5", Porcentajes = 35 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 65 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 100 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseMPvs3BetBB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x22", Porcentajes = 27 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 73 },
                new Hands { Hand = "ATs", Action = "4Bet x22", Porcentajes = 12 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 88 },
                new Hands { Hand = "A9s", Action = "4Bet x22", Porcentajes = 50 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 17 },
                new Hands { Hand = "A8s", Action = "4Bet x22", Porcentajes = 49 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 29 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 22 },
                new Hands { Hand = "A7s", Action = "4Bet x22", Porcentajes = 6 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 94 },
                new Hands { Hand = "A6s", Action = "4Bet x22", Porcentajes = 15 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "A5s", Action = "4Bet x22", Porcentajes = 6 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 64 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "A3s", Action = "4Bet x22", Porcentajes = 12 },
                new Hands { Hand = "A3s", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "A2s", Action = "4Bet x22", Porcentajes = 23 },
                new Hands { Hand = "A2s", Action = "Fold", Porcentajes = 77 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 50 },
                new Hands { Hand = "AKo", Action = "4Bet x22", Porcentajes = 3 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 47 },
                new Hands { Hand = "KK", Action = "All-In", Porcentajes = 32 },
                new Hands { Hand = "KK", Action = "4Bet x22", Porcentajes = 65 },
                new Hands { Hand = "KK", Action = "Call", Porcentajes = 3 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "KJs", Action = "4Bet x22", Porcentajes = 42 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 58 },
                new Hands { Hand = "KTs", Action = "4Bet x22", Porcentajes = 52 },
                new Hands { Hand = "KTs", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 8 },
                new Hands { Hand = "K9s", Action = "4Bet x22", Porcentajes = 22 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "K5s", Action = "4Bet x22", Porcentajes = 7 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 93 },
                new Hands { Hand = "AQo", Action = "4Bet x22", Porcentajes = 22 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "QJs", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "QJs", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "JJ", Action = "4Bet x22", Porcentajes = 8 },
                new Hands { Hand = "JJ", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "JJ", Action = "Fold", Porcentajes = 22 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 3 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 97 },
                new Hands { Hand = "TT", Action = "4Bet x22", Porcentajes = 7 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 53 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 62 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 58 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 42 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 32 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "54s", Action = "4Bet x22", Porcentajes = 70 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 67 },
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseMPvs3BetSB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x20.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x20.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x20.5", Porcentajes = 25 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 75 },
                new Hands { Hand = "ATs", Action = "4Bet x20.5", Porcentajes = 25 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 75 },
                new Hands { Hand = "A9s", Action = "4Bet x20.5", Porcentajes = 42 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 58 },
                new Hands { Hand = "A8s", Action = "4Bet x20.5", Porcentajes = 45 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 5 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "A7s", Action = "4Bet x20.5", Porcentajes = 12 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "A5s", Action = "4Bet x20.5", Porcentajes = 22 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 38 },
                new Hands { Hand = "A4s", Action = "4Bet x20.5", Porcentajes = 33 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 12 },
                new Hands { Hand = "AKo", Action = "4Bet x20.5", Porcentajes = 28 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "KK", Action = "All-In", Porcentajes = 2 },
                new Hands { Hand = "KK", Action = "4Bet x20.5", Porcentajes = 98 },
                new Hands { Hand = "KQs", Action = "4Bet x20.5", Porcentajes = 2 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 98 },
                new Hands { Hand = "KJs", Action = "4Bet x20.5", Porcentajes = 75 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 25 },
                new Hands { Hand = "KTs", Action = "4Bet x20.5", Porcentajes = 48 },
                new Hands { Hand = "KTs", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 35 },
                new Hands { Hand = "K9s", Action = "4Bet x20.5", Porcentajes = 13 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "K5s", Action = "4Bet x20.5", Porcentajes = 22 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "AQo", Action = "4Bet x20.5", Porcentajes = 45 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "QQ", Action = "4Bet x20.5", Porcentajes = 10 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 90 },
                new Hands { Hand = "QJs", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "QJs", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 13 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "JJ", Action = "4Bet x20.5", Porcentajes = 28 },
                new Hands { Hand = "JJ", Action = "Marginal Call", Porcentajes = 72 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "TT", Action = "4Bet x20.5", Porcentajes = 12 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 55 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 33 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "4Bet x20.5", Porcentajes = 12 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 37 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 51 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 32 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 28 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 72 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 63 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 37 },
                new Hands { Hand = "33", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "33", Action = "Fold", Porcentajes = 52 },
                new Hands { Hand = "22", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "22", Action = "Fold", Porcentajes = 30 },
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseMPvs3BetBTN(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x19", Porcentajes = 37 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 63 },
                new Hands { Hand = "ATs", Action = "4Bet x19", Porcentajes = 65 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 35 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "A8s", Action = "4Bet x19", Porcentajes = 42 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "A7s", Action = "4Bet x19", Porcentajes = 18 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "A6s", Action = "4Bet x19", Porcentajes = 2 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "A5s", Action = "4Bet x19", Porcentajes = 33 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 28 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 39 },
                new Hands { Hand = "A4s", Action = "4Bet x19", Porcentajes = 38 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 13 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 49 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 66 },
                new Hands { Hand = "AKo", Action = "4Bet x19", Porcentajes = 32 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 2 },
                new Hands { Hand = "KK", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "4Bet x19", Porcentajes = 43 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 57 },
                new Hands { Hand = "KJs", Action = "4Bet x19", Porcentajes = 88 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 12 },
                new Hands { Hand = "KTs", Action = "4Bet x19", Porcentajes = 73 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 27 },
                new Hands { Hand = "K9s", Action = "4Bet x19", Porcentajes = 13 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "K6s", Action = "4Bet x19", Porcentajes = 7 },
                new Hands { Hand = "K6s", Action = "Fold", Porcentajes = 93 },
                new Hands { Hand = "K5s", Action = "4Bet x19", Porcentajes = 72 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 28 },
                new Hands { Hand = "K4s", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AQo", Action = "4Bet x19", Porcentajes = 90 },
                new Hands { Hand = "AQo", Action = "Call", Porcentajes = 10 },
                new Hands { Hand = "KQo", Action = "4Bet x19", Porcentajes = 10 },
                new Hands { Hand = "KQo", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "QQ", Action = "All-In", Porcentajes = 26 },
                new Hands { Hand = "QQ", Action = "4Bet x19", Porcentajes = 72 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 2 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 92 },
                new Hands { Hand = "JJ", Action = "4Bet x19", Porcentajes = 50 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 50 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 20 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "TT", Action = "4Bet x19", Porcentajes = 45 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "99", Action = "4Bet x19", Porcentajes = 12 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 62 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "76s", Action = "Marginal Call", Porcentajes = 85 },
                new Hands { Hand = "76s", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 70 },                
                new Hands { Hand = "65s", Action = "4Bet x19", Porcentajes = 2 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 80 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 18 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "54s", Action = "4Bet x19", Porcentajes = 12 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 88 },
                new Hands { Hand = "44", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 100 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseMPvs3BetCO(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x19", Porcentajes = 45 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 55 },
                new Hands { Hand = "ATs", Action = "4Bet x19", Porcentajes = 40 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "A8s", Action = "4Bet x19", Porcentajes = 33 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "A7s", Action = "4Bet x19", Porcentajes = 22 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "A5s", Action = "4Bet x19", Porcentajes = 52 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 10 },
                new Hands { Hand = "A4s", Action = "4Bet x19", Porcentajes = 45 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 38 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 76 },
                new Hands { Hand = "AKo", Action = "4Bet x19", Porcentajes = 22 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 2 },
                new Hands { Hand = "KK", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "4Bet x19", Porcentajes = 48 },
                new Hands { Hand = "KQs", Action = "Call", Porcentajes = 52 },
                new Hands { Hand = "KJs", Action = "4Bet x19", Porcentajes = 77 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 27 },
                new Hands { Hand = "KTs", Action = "4Bet x19", Porcentajes = 60 },
                new Hands { Hand = "KTs", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "K9s", Action = "4Bet x19", Porcentajes = 3 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 97 },
                new Hands { Hand = "K6s", Action = "4Bet x19", Porcentajes = 33 },
                new Hands { Hand = "K6s", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "K6s", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "K5s", Action = "4Bet x19", Porcentajes = 67 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 33 },
                new Hands { Hand = "K4s", Action = "4Bet x19", Porcentajes = 100 },
                new Hands { Hand = "AQo", Action = "4Bet x19", Porcentajes = 78 },
                new Hands { Hand = "AQo", Action = "Marginal Call", Porcentajes = 22 },
                new Hands { Hand = "QQ", Action = "All-In", Porcentajes = 40 },
                new Hands { Hand = "QQ", Action = "4Bet x19", Porcentajes = 57 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 3 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "JJ", Action = "4Bet x19", Porcentajes = 38 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 62 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 62 },
                new Hands { Hand = "TT", Action = "4Bet x19", Porcentajes = 15 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 70 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "99", Action = "4Bet x19", Porcentajes = 2 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "88", Action = "4Bet x19", Porcentajes = 2 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 58 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 42 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 45 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 62 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 37 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 63 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 100 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseEPvs3BetBB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x22", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x22", Porcentajes = 85 },
                new Hands { Hand = "AKs", Action = "Call", Porcentajes = 15 },
                new Hands { Hand = "AQs", Action = "4Bet x22", Porcentajes = 5 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 95 },
                new Hands { Hand = "AJs", Action = "4Bet x22", Porcentajes = 52 },
                new Hands { Hand = "AJs", Action = "Marginal Call", Porcentajes = 47 },
                new Hands { Hand = "AJs", Action = "Fold", Porcentajes = 1 },
                new Hands { Hand = "ATs", Action = "4Bet x22", Porcentajes = 25 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 75 },
                new Hands { Hand = "A9s", Action = "4Bet x22", Porcentajes = 65 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 23 },
                new Hands { Hand = "A8s", Action = "4Bet x22", Porcentajes = 15 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 5 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "A7s", Action = "4Bet x22", Porcentajes = 17 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 68 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 32 },
                new Hands { Hand = "A2s", Action = "4Bet x22", Porcentajes = 20 },
                new Hands { Hand = "A2s", Action = "Fold", Porcentajes = 80 },
                new Hands { Hand = "AKo", Action = "4Bet x22", Porcentajes = 48 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 52 },
                new Hands { Hand = "KK", Action = "4Bet x22", Porcentajes = 87 },
                new Hands { Hand = "KK", Action = "Call", Porcentajes = 13 },
                new Hands { Hand = "KQs", Action = "4Bet x22", Porcentajes = 8 },
                new Hands { Hand = "KQs", Action = "Marginal Call", Porcentajes = 52 },
                new Hands { Hand = "KQs", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "KJs", Action = "4Bet x22", Porcentajes = 20 },
                new Hands { Hand = "KJs", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 42 },
                new Hands { Hand = "KTs", Action = "4Bet x22", Porcentajes = 25 },
                new Hands { Hand = "KTs", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "QTs", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "QTs", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "JJ", Action = "4Bet x22", Porcentajes = 5 },
                new Hands { Hand = "JJ", Action = "Marginal Call", Porcentajes = 45 },
                new Hands { Hand = "JJ", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 5 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 95 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 28 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 72 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 23 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 77 },
                new Hands { Hand = "87s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 22 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 25 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 75 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 85 },
                new Hands { Hand = "54s", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "54s", Action = "Fold", Porcentajes = 62 },
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseEPvs3BetSB(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x20.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x20.5", Porcentajes = 87 },
                new Hands { Hand = "AKs", Action = "Call", Porcentajes = 13 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x20.5", Porcentajes = 60 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 40 },
                new Hands { Hand = "ATs", Action = "4Bet x20.5", Porcentajes = 23 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 75 },
                new Hands { Hand = "ATs", Action = "Fold", Porcentajes = 2 },
                new Hands { Hand = "A9s", Action = "4Bet x20.5", Porcentajes = 25 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 2 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 73 },
                new Hands { Hand = "A8s", Action = "4Bet x20.5", Porcentajes = 17 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "A7s", Action = "4Bet x20.5", Porcentajes = 17 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 47 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 53 },
                new Hands { Hand = "A4s", Action = "4Bet x20.5", Porcentajes = 22 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "A3s", Action = "4Bet x20.5", Porcentajes = 52 },
                new Hands { Hand = "A3s", Action = "Fold", Porcentajes = 48 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 53 },
                new Hands { Hand = "AKo", Action = "4Bet x20.5", Porcentajes = 1 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 46 },
                new Hands { Hand = "KK", Action = "All-In", Porcentajes = 27 },
                new Hands { Hand = "KK", Action = "4Bet x20.5", Porcentajes = 67 },
                new Hands { Hand = "KK", Action = "Call", Porcentajes = 6 },
                new Hands { Hand = "KQs", Action = "Marginal Call", Porcentajes = 43 },
                new Hands { Hand = "KQs", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "KJs", Action = "4Bet x20.5", Porcentajes = 45 },
                new Hands { Hand = "KJs", Action = "Marginal Call", Porcentajes = 38 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 17 },
                new Hands { Hand = "KTs", Action = "4Bet x20.5", Porcentajes = 58 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 42 },
                new Hands { Hand = "K9s", Action = "4Bet x20.5", Porcentajes = 12 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "K5s", Action = "4Bet x20.5", Porcentajes = 32 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "AQo", Action = "4Bet x20.5", Porcentajes = 7 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 93 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "JJ", Action = "4Bet x20.5", Porcentajes = 7 },
                new Hands { Hand = "JJ", Action = "Marginal Call", Porcentajes = 58 },
                new Hands { Hand = "JJ", Action = "Fold", Porcentajes = 35 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 35 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 65 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 12 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 88 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 30 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "87s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 17 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 83 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 23 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 77 },
                new Hands { Hand = "65s", Action = "Marginal Call", Porcentajes = 97 },
                new Hands { Hand = "65s", Action = "Fold", Porcentajes = 3 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 10 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 90 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Marginal Call", Porcentajes = 52 },
                new Hands { Hand = "44", Action = "Fold", Porcentajes = 48 },
                new Hands { Hand = "33", Action = "Marginal Call", Porcentajes = 40 },
                new Hands { Hand = "33", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "22", Action = "Marginal Call", Porcentajes = 28 },
                new Hands { Hand = "22", Action = "Fold", Porcentajes = 72 },
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseEPvs3BetBTN(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x19.5", Porcentajes = 58 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 42 },
                new Hands { Hand = "ATs", Action = "4Bet x19.5", Porcentajes = 33 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 67 },
                new Hands { Hand = "A9s", Action = "4Bet x19.5", Porcentajes = 3 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "A8s", Action = "4Bet x19.5", Porcentajes = 22 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "A7s", Action = "4Bet x19.5", Porcentajes = 40 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "A6s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "A5s", Action = "4Bet x19.5", Porcentajes = 27 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 51 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 16 },
                new Hands { Hand = "A4s", Action = "4Bet x19.5", Porcentajes = 65 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 8 },
                new Hands { Hand = "A3s", Action = "4Bet x19.5", Porcentajes = 13 },
                new Hands { Hand = "A3s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 68 },
                new Hands { Hand = "AKo", Action = "4Bet x19.5", Porcentajes = 15 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 17 },
                new Hands { Hand = "KK", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "KQs", Action = "Fold", Porcentajes = 52 },
                new Hands { Hand = "KJs", Action = "4Bet x19.5", Porcentajes = 73 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 27 },
                new Hands { Hand = "KTs", Action = "4Bet x19.5", Porcentajes = 65 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 35 },
                new Hands { Hand = "K9s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "K7s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "K7s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "K6s", Action = "4Bet x19.5", Porcentajes = 22 },
                new Hands { Hand = "K6s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "K5s", Action = "4Bet x19.5", Porcentajes = 60 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "AQo", Action = "4Bet x19.5", Porcentajes = 48 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 52 },
                new Hands { Hand = "QQ", Action = "All-In", Porcentajes = 33 },
                new Hands { Hand = "QQ", Action = "4Bet x19.5", Porcentajes = 7 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "JJ", Action = "4Bet x19.5", Porcentajes = 28 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 72 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 32 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "TT", Action = "4Bet x19.5", Porcentajes = 3 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 67 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 45 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 77 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 23 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 43 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 85 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 50 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 75 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 25 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 100 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        private static string OpenRaiseEPvs3BetCO(string hand)
        {

            var hands = new List<Hands>
            {
                new Hands { Hand = "AA", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "AKs", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "AQs", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "AJs", Action = "4Bet x19.5", Porcentajes = 58 },
                new Hands { Hand = "AJs", Action = "Call", Porcentajes = 42 },
                new Hands { Hand = "ATs", Action = "4Bet x19.5", Porcentajes = 33 },
                new Hands { Hand = "ATs", Action = "Call", Porcentajes = 67 },
                new Hands { Hand = "A9s", Action = "4Bet x19.5", Porcentajes = 3 },
                new Hands { Hand = "A9s", Action = "Marginal Call", Porcentajes = 15 },
                new Hands { Hand = "A9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "A8s", Action = "4Bet x19.5", Porcentajes = 22 },
                new Hands { Hand = "A8s", Action = "Marginal Call", Porcentajes = 8 },
                new Hands { Hand = "A8s", Action = "Fold", Porcentajes = 70 },
                new Hands { Hand = "A7s", Action = "4Bet x19.5", Porcentajes = 40 },
                new Hands { Hand = "A7s", Action = "Fold", Porcentajes = 60 },
                new Hands { Hand = "A6s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "A6s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "A5s", Action = "4Bet x19.5", Porcentajes = 27 },
                new Hands { Hand = "A5s", Action = "Marginal Call", Porcentajes = 51 },
                new Hands { Hand = "A5s", Action = "Fold", Porcentajes = 16 },
                new Hands { Hand = "A4s", Action = "4Bet x19.5", Porcentajes = 65 },
                new Hands { Hand = "A4s", Action = "Marginal Call", Porcentajes = 27 },
                new Hands { Hand = "A4s", Action = "Fold", Porcentajes = 8 },
                new Hands { Hand = "A3s", Action = "4Bet x19.5", Porcentajes = 13 },
                new Hands { Hand = "A3s", Action = "Fold", Porcentajes = 87 },
                new Hands { Hand = "AKo", Action = "All-In", Porcentajes = 68 },
                new Hands { Hand = "AKo", Action = "4Bet x19.5", Porcentajes = 15 },
                new Hands { Hand = "AKo", Action = "Call", Porcentajes = 17 },
                new Hands { Hand = "KK", Action = "4Bet x19.5", Porcentajes = 100 },
                new Hands { Hand = "KQs", Action = "Marginal Call", Porcentajes = 48 },
                new Hands { Hand = "KQs", Action = "Fold", Porcentajes = 52 },
                new Hands { Hand = "KJs", Action = "4Bet x19.5", Porcentajes = 73 },
                new Hands { Hand = "KJs", Action = "Call", Porcentajes = 27 },
                new Hands { Hand = "KTs", Action = "4Bet x19.5", Porcentajes = 65 },
                new Hands { Hand = "KTs", Action = "Fold", Porcentajes = 35 },
                new Hands { Hand = "K9s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "K9s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "K7s", Action = "4Bet x19.5", Porcentajes = 2 },
                new Hands { Hand = "K7s", Action = "Fold", Porcentajes = 98 },
                new Hands { Hand = "K6s", Action = "4Bet x19.5", Porcentajes = 22 },
                new Hands { Hand = "K6s", Action = "Fold", Porcentajes = 78 },
                new Hands { Hand = "K5s", Action = "4Bet x19.5", Porcentajes = 60 },
                new Hands { Hand = "K5s", Action = "Fold", Porcentajes = 40 },
                new Hands { Hand = "AQo", Action = "4Bet x19.5", Porcentajes = 48 },
                new Hands { Hand = "AQo", Action = "Fold", Porcentajes = 52 },
                new Hands { Hand = "QQ", Action = "All-In", Porcentajes = 33 },
                new Hands { Hand = "QQ", Action = "4Bet x19.5", Porcentajes = 7 },
                new Hands { Hand = "QQ", Action = "Call", Porcentajes = 60 },
                new Hands { Hand = "JJ", Action = "4Bet x19.5", Porcentajes = 28 },
                new Hands { Hand = "JJ", Action = "Call", Porcentajes = 72 },
                new Hands { Hand = "JTs", Action = "Marginal Call", Porcentajes = 32 },
                new Hands { Hand = "JTs", Action = "Fold", Porcentajes = 68 },
                new Hands { Hand = "TT", Action = "4Bet x19.5", Porcentajes = 3 },
                new Hands { Hand = "TT", Action = "Marginal Call", Porcentajes = 67 },
                new Hands { Hand = "TT", Action = "Fold", Porcentajes = 30 },
                new Hands { Hand = "T9s", Action = "Marginal Call", Porcentajes = 18 },
                new Hands { Hand = "T9s", Action = "Fold", Porcentajes = 82 },
                new Hands { Hand = "99", Action = "Marginal Call", Porcentajes = 45 },
                new Hands { Hand = "99", Action = "Fold", Porcentajes = 55 },
                new Hands { Hand = "98s", Action = "Marginal Call", Porcentajes = 77 },
                new Hands { Hand = "98s", Action = "Fold", Porcentajes = 23 },
                new Hands { Hand = "88", Action = "Marginal Call", Porcentajes = 43 },
                new Hands { Hand = "88", Action = "Fold", Porcentajes = 57 },
                new Hands { Hand = "87s", Action = "Marginal Call", Porcentajes = 85 },
                new Hands { Hand = "87s", Action = "Fold", Porcentajes = 15 },
                new Hands { Hand = "77", Action = "Marginal Call", Porcentajes = 33 },
                new Hands { Hand = "77", Action = "Fold", Porcentajes = 67 },
                new Hands { Hand = "76s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "66", Action = "Marginal Call", Porcentajes = 50 },
                new Hands { Hand = "66", Action = "Fold", Porcentajes = 50 },
                new Hands { Hand = "65s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "55", Action = "Marginal Call", Porcentajes = 75 },
                new Hands { Hand = "55", Action = "Fold", Porcentajes = 25 },
                new Hands { Hand = "54s", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "44", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "33", Action = "Call", Porcentajes = 100 },
                new Hands { Hand = "22", Action = "Call", Porcentajes = 100 }
            };


            return ObtainActionHelper.ObtainAction(hands, hand);
        }
        #endregion



    }
}
