using OpenScrape.App.Helpers;

namespace OpenScrape.App.Tables
{
    public static class RaiseVsSBLimp
    {
        #region Hands

        public static string GetBigBlindvsSBCall(string hand)
        {
            var hands = new List<Hands>
            {
                new Hands{ Hand = "AA", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "AKs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "AQs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "AJs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "ATs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "A9s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "A8s", Action = "Raise Over Limpers x3.4", Porcentajes =  76 },
                new Hands{ Hand = "A8s", Action = "Check", Porcentajes =  24 },
                new Hands{ Hand = "A7s", Action = "Raise Over Limpers x3.4", Porcentajes =  45 },
                new Hands{ Hand = "A7s", Action = "Check", Porcentajes =  55 },
                new Hands{ Hand = "A6s", Action = "Raise Over Limpers x3.4", Porcentajes =  21 },
                new Hands{ Hand = "A6s", Action = "Check", Porcentajes =  79 },
                new Hands{ Hand = "A5s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "A4s", Action = "Raise Over Limpers x3.4", Porcentajes =  97 },
                new Hands{ Hand = "A4s", Action = "Check", Porcentajes =  3 },
                new Hands{ Hand = "A3s", Action = "Raise Over Limpers x3.4", Porcentajes =  49 },
                new Hands{ Hand = "A3s", Action = "Check", Porcentajes =  51 },
                new Hands{ Hand = "A2s", Action = "Raise Over Limpers x3.4", Porcentajes =  21 },
                new Hands{ Hand = "A2s", Action = "Check", Porcentajes =  79 },
                new Hands{ Hand = "AKo", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "KK", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "KQs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "KJs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "KTs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "K9s", Action = "Raise Over Limpers x3.4", Porcentajes =  72 },
                new Hands{ Hand = "K9s", Action = "Check", Porcentajes =  28 },
                new Hands{ Hand = "K6s", Action = "Raise Over Limpers x3.4", Porcentajes =  33 },
                new Hands{ Hand = "K6s", Action = "Check", Porcentajes =  67 },
                new Hands{ Hand = "K5s", Action = "Raise Over Limpers x3.4", Porcentajes =  39 },
                new Hands{ Hand = "K5s", Action = "Check", Porcentajes =  61 },
                new Hands{ Hand = "K4s", Action = "Raise Over Limpers x3.4", Porcentajes =  67 },
                new Hands{ Hand = "K4s", Action = "Check", Porcentajes =  33 },
                new Hands{ Hand = "K3s", Action = "Raise Over Limpers x3.4", Porcentajes =  77 },
                new Hands{ Hand = "K3s", Action = "Check", Porcentajes =  23 },
                new Hands{ Hand = "K2s", Action = "Raise Over Limpers x3.4", Porcentajes =  59 },
                new Hands{ Hand = "K2s", Action = "Check", Porcentajes =  41 },
                new Hands{ Hand = "AQo", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "KQo", Action = "Raise Over Limpers x3.4", Porcentajes =  73 },
                new Hands{ Hand = "KQo", Action = "Check", Porcentajes =  27 },
                new Hands{ Hand = "QQ", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "QJs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "QTs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "Q9s", Action = "Raise Over Limpers x3.4", Porcentajes =  19 },
                new Hands{ Hand = "Q9s", Action = "Check", Porcentajes =  81 },
                new Hands{ Hand = "Q5s", Action = "Raise Over Limpers x3.4", Porcentajes =  4 },
                new Hands{ Hand = "Q5s", Action = "Check", Porcentajes =  96 },
                new Hands{ Hand = "Q4s", Action = "Raise Over Limpers x3.4", Porcentajes =  46 },
                new Hands{ Hand = "Q4s", Action = "Check", Porcentajes =  54 },
                new Hands{ Hand = "Q3s", Action = "Raise Over Limpers x3.4", Porcentajes =  34 },
                new Hands{ Hand = "Q3s", Action = "Check", Porcentajes =  66 },
                new Hands{ Hand = "AJo", Action = "Raise Over Limpers x3.4", Porcentajes =  74 },
                new Hands{ Hand = "AJo", Action = "Check", Porcentajes =  26 },
                new Hands{ Hand = "KJo", Action = "Raise Over Limpers x3.4", Porcentajes =  31 },
                new Hands{ Hand = "KJo", Action = "Check", Porcentajes =  69 },
                new Hands{ Hand = "QJo", Action = "Raise Over Limpers x3.4", Porcentajes =  33 },
                new Hands{ Hand = "QJo", Action = "Check", Porcentajes =  67 },
                new Hands{ Hand = "JJ", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "JTs", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "J9s", Action = "Raise Over Limpers x3.4", Porcentajes =  5 },
                new Hands{ Hand = "J9s", Action = "Check", Porcentajes =  95 },
                new Hands{ Hand = "J5s", Action = "Raise Over Limpers x3.4", Porcentajes =  19 },
                new Hands{ Hand = "J5s", Action = "Check", Porcentajes =  81 },
                new Hands{ Hand = "J4s", Action = "Raise Over Limpers x3.4", Porcentajes =  28 },
                new Hands{ Hand = "J4s", Action = "Check", Porcentajes =  72 },
                new Hands{ Hand = "J3s", Action = "Raise Over Limpers x3.4", Porcentajes =  56 },
                new Hands{ Hand = "J3s", Action = "Check", Porcentajes =  44 },
                new Hands{ Hand = "ATo", Action = "Raise Over Limpers x3.4", Porcentajes =  60 },
                new Hands{ Hand = "ATo", Action = "Check", Porcentajes =  40 },
                new Hands{ Hand = "KTo", Action = "Raise Over Limpers x3.4", Porcentajes =  36 },
                new Hands{ Hand = "KTo", Action = "Check", Porcentajes =  64 },
                new Hands{ Hand = "QTo", Action = "Raise Over Limpers x3.4", Porcentajes =  33 },
                new Hands{ Hand = "QTo", Action = "Check", Porcentajes =  67 },
                new Hands{ Hand = "JTo", Action = "Raise Over Limpers x3.4", Porcentajes =  26 },
                new Hands{ Hand = "JTo", Action = "Check", Porcentajes =  74 },
                new Hands{ Hand = "TT", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "T9s", Action = "Raise Over Limpers x3.4", Porcentajes =  51 },
                new Hands{ Hand = "T9s", Action = "Check", Porcentajes =  49 },
                new Hands{ Hand = "T8s", Action = "Raise Over Limpers x3.4", Porcentajes =  11 },
                new Hands{ Hand = "T8s", Action = "Check", Porcentajes =  89 },
                new Hands{ Hand = "T7s", Action = "Raise Over Limpers x3.4", Porcentajes =  13 },
                new Hands{ Hand = "T7s", Action = "Check", Porcentajes =  87 },
                new Hands{ Hand = "T6s", Action = "Raise Over Limpers x3.4", Porcentajes =  2 },
                new Hands{ Hand = "T6s", Action = "Check", Porcentajes =  98 },
                new Hands{ Hand = "T5s", Action = "Raise Over Limpers x3.4", Porcentajes =  78 },
                new Hands{ Hand = "T5s", Action = "Check", Porcentajes =  22 },
                new Hands{ Hand = "T4s", Action = "Raise Over Limpers x3.4", Porcentajes =  93 },
                new Hands{ Hand = "T4s", Action = "Check", Porcentajes =  7 },
                new Hands{ Hand = "T3s", Action = "Raise Over Limpers x3.4", Porcentajes =  10 },
                new Hands{ Hand = "T3s", Action = "Check", Porcentajes =  90 },
                new Hands{ Hand = "T2s", Action = "Raise Over Limpers x3.4", Porcentajes =  28 },
                new Hands{ Hand = "T2s", Action = "Check", Porcentajes =  72 },
                new Hands{ Hand = "A9o", Action = "Raise Over Limpers x3.4", Porcentajes =  55 },
                new Hands{ Hand = "A9o", Action = "Check", Porcentajes =  45 },
                new Hands{ Hand = "K9o", Action = "Raise Over Limpers x3.4", Porcentajes =  14 },
                new Hands{ Hand = "K9o", Action = "Check", Porcentajes =  86 },
                new Hands{ Hand = "Q9o", Action = "Raise Over Limpers x3.4", Porcentajes =  48 },
                new Hands{ Hand = "Q9o", Action = "Check", Porcentajes =  52 },
                new Hands{ Hand = "J9o", Action = "Raise Over Limpers x3.4", Porcentajes =  63 },
                new Hands{ Hand = "J9o", Action = "Check", Porcentajes =  37 },
                new Hands{ Hand = "T9o", Action = "Raise Over Limpers x3.4", Porcentajes =  48 },
                new Hands{ Hand = "T9o", Action = "Check", Porcentajes =  52 },
                new Hands{ Hand = "99", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "98s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "97s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "96s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "95s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "94s", Action = "Raise Over Limpers x3.4", Porcentajes =  25 },
                new Hands{ Hand = "94s", Action = "Check", Porcentajes =  75 },
                new Hands{ Hand = "93s", Action = "Raise Over Limpers x3.4", Porcentajes =  81 },
                new Hands{ Hand = "93s", Action = "Check", Porcentajes =  19 },
                new Hands{ Hand = "92s", Action = "Raise Over Limpers x3.4", Porcentajes =  98 },
                new Hands{ Hand = "92s", Action = "Check", Porcentajes =  2 },
                new Hands{ Hand = "K8o", Action = "Raise Over Limpers x3.4", Porcentajes =  5 },
                new Hands{ Hand = "K8o", Action = "Check", Porcentajes =  95 },
                new Hands{ Hand = "Q8o", Action = "Raise Over Limpers x3.4", Porcentajes =  40 },
                new Hands{ Hand = "Q8o", Action = "Check", Porcentajes =  60 },
                new Hands{ Hand = "J8o", Action = "Raise Over Limpers x3.4", Porcentajes =  67 },
                new Hands{ Hand = "J8o", Action = "Check", Porcentajes =  33 },
                new Hands{ Hand = "T8o", Action = "Raise Over Limpers x3.4", Porcentajes =  71 },
                new Hands{ Hand = "T8o", Action = "Check", Porcentajes =  29 },
                new Hands{ Hand = "98o", Action = "Raise Over Limpers x3.4", Porcentajes =  54 },
                new Hands{ Hand = "98o", Action = "Check", Porcentajes =  46 },
                new Hands{ Hand = "88", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "87s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "86s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "85s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "84s", Action = "Raise Over Limpers x3.4", Porcentajes =  91 },
                new Hands{ Hand = "84s", Action = "Check", Porcentajes =  9 },
                new Hands{ Hand = "82s", Action = "Raise Over Limpers x3.4", Porcentajes =  57 },
                new Hands{ Hand = "82s", Action = "Check", Porcentajes =  43 },
                new Hands{ Hand = "A7o", Action = "Raise Over Limpers x3.4", Porcentajes =  7 },
                new Hands{ Hand = "A7o", Action = "Check", Porcentajes =  93 },
                new Hands{ Hand = "K7o", Action = "Raise Over Limpers x3.4", Porcentajes =  54 },
                new Hands{ Hand = "K7o", Action = "Check", Porcentajes =  46 },
                new Hands{ Hand = "Q7o", Action = "Raise Over Limpers x3.4", Porcentajes =  72 },
                new Hands{ Hand = "Q7o", Action = "Check", Porcentajes =  28 },
                new Hands{ Hand = "J7o", Action = "Raise Over Limpers x3.4", Porcentajes =  41 },
                new Hands{ Hand = "J7o", Action = "Check", Porcentajes =  59 },
                new Hands{ Hand = "T7o", Action = "Raise Over Limpers x3.4", Porcentajes =  47 },
                new Hands{ Hand = "T7o", Action = "Check", Porcentajes =  53 },
                new Hands{ Hand = "97o", Action = "Raise Over Limpers x3.4", Porcentajes =  39 },
                new Hands{ Hand = "97o", Action = "Check", Porcentajes =  61 },
                new Hands{ Hand = "87o", Action = "Raise Over Limpers x3.4", Porcentajes =  55 },
                new Hands{ Hand = "87o", Action = "Check", Porcentajes =  45 },
                new Hands{ Hand = "77", Action = "Raise Over Limpers x3.4", Porcentajes =  88 },
                new Hands{ Hand = "77", Action = "Check", Porcentajes =  12 },
                new Hands{ Hand = "76s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "75s", Action = "Raise Over Limpers x3.4", Porcentajes =  89 },
                new Hands{ Hand = "75s", Action = "Check", Porcentajes =  11 },
                new Hands{ Hand = "74s", Action = "Raise Over Limpers x3.4", Porcentajes =  100 },
                new Hands{ Hand = "73s", Action = "Raise Over Limpers x3.4", Porcentajes =  76 },
                new Hands{ Hand = "73s", Action = "Check", Porcentajes =  24 },
                new Hands{ Hand = "A6o", Action = "Raise Over Limpers x3.4", Porcentajes =  41 },
                new Hands{ Hand = "A6o", Action = "Check", Porcentajes =  59 },
                new Hands{ Hand = "K6o", Action = "Raise Over Limpers x3.4", Porcentajes =  72 },
                new Hands{ Hand = "K6o", Action = "Check", Porcentajes =  28 },
                new Hands{ Hand = "Q6o", Action = "Raise Over Limpers x3.4", Porcentajes =  79 },
                new Hands{ Hand = "Q6o", Action = "Check", Porcentajes =  21 },
                new Hands{ Hand = "J6o", Action = "Raise Over Limpers x3.4", Porcentajes =  45 },
                new Hands{ Hand = "J6o", Action = "Check", Porcentajes =  55 },
                new Hands{ Hand = "T6o", Action = "Raise Over Limpers x3.4", Porcentajes =  50 },
                new Hands{ Hand = "T6o", Action = "Check", Porcentajes =  50 },
                new Hands{ Hand = "96o", Action = "Raise Over Limpers x3.4", Porcentajes =  40 },
                new Hands{ Hand = "96o", Action = "Check", Porcentajes =  60 },
                new Hands{ Hand = "86o", Action = "Raise Over Limpers x3.4", Porcentajes =  45 },
                new Hands{ Hand = "86o", Action = "Check", Porcentajes =  55 },
                new Hands{ Hand = "76o", Action = "Raise Over Limpers x3.4", Porcentajes =  30 },
                new Hands{ Hand = "76o", Action = "Check", Porcentajes =  70 },
                new Hands{ Hand = "66", Action = "Raise Over Limpers x3.4", Porcentajes =  78 },
                new Hands{ Hand = "66", Action = "Check", Porcentajes =  22 },
                new Hands{ Hand = "65s", Action = "Raise Over Limpers x3.4", Porcentajes =  39 },
                new Hands{ Hand = "65s", Action = "Check", Porcentajes =  61 },
                new Hands{ Hand = "64s", Action = "Raise Over Limpers x3.4", Porcentajes =  89 },
                new Hands{ Hand = "64s", Action = "Check", Porcentajes =  11 },
                new Hands{ Hand = "63s", Action = "Raise Over Limpers x3.4", Porcentajes =  75 },
                new Hands{ Hand = "63s", Action = "Check", Porcentajes =  25 },
                new Hands{ Hand = "62s", Action = "Raise Over Limpers x3.4", Porcentajes =  30 },
                new Hands{ Hand = "62s", Action = "Check", Porcentajes =  70 },
                new Hands{ Hand = "A5o", Action = "Raise Over Limpers x3.4", Porcentajes =  45 },
                new Hands{ Hand = "A5o", Action = "Check", Porcentajes =  55 },
                new Hands{ Hand = "K5o", Action = "Raise Over Limpers x3.4", Porcentajes =  51 },
                new Hands{ Hand = "K5o", Action = "Check", Porcentajes =  49 },
                new Hands{ Hand = "Q5o", Action = "Raise Over Limpers x3.4", Porcentajes =  38 },
                new Hands{ Hand = "Q5o", Action = "Check", Porcentajes =  62 },
                new Hands{ Hand = "J5o", Action = "Raise Over Limpers x3.4", Porcentajes =  34 },
                new Hands{ Hand = "J5o", Action = "Check", Porcentajes =  66 },
                new Hands{ Hand = "T5o", Action = "Raise Over Limpers x3.4", Porcentajes =  11 },
                new Hands{ Hand = "T5o", Action = "Check", Porcentajes =  89 },
                new Hands{ Hand = "95o", Action = "Raise Over Limpers x3.4", Porcentajes =  8 },
                new Hands{ Hand = "95o", Action = "Check", Porcentajes =  92 },
                new Hands{ Hand = "85o", Action = "Raise Over Limpers x3.4", Porcentajes =  20 },
                new Hands{ Hand = "85o", Action = "Check", Porcentajes =  80 },
                new Hands{ Hand = "75o", Action = "Raise Over Limpers x3.4", Porcentajes =  34 },
                new Hands{ Hand = "75o", Action = "Check", Porcentajes =  66 },
                new Hands{ Hand = "65o", Action = "Raise Over Limpers x3.4", Porcentajes =  44 },
                new Hands{ Hand = "65o", Action = "Check", Porcentajes =  56 },
                new Hands{ Hand = "55", Action = "Raise Over Limpers x3.4", Porcentajes =  69 },
                new Hands{ Hand = "55", Action = "Check", Porcentajes =  31 },
                new Hands{ Hand = "54s", Action = "Raise Over Limpers x3.4", Porcentajes =  37 },
                new Hands{ Hand = "54s", Action = "Check", Porcentajes =  63 },
                new Hands{ Hand = "53s", Action = "Raise Over Limpers x3.4", Porcentajes =  47 },
                new Hands{ Hand = "53s", Action = "Check", Porcentajes =  53 },
                new Hands{ Hand = "52s", Action = "Raise Over Limpers x3.4", Porcentajes =  65 },
                new Hands{ Hand = "52s", Action = "Check", Porcentajes =  35 },
                new Hands{ Hand = "A4o", Action = "Raise Over Limpers x3.4", Porcentajes =  25 },
                new Hands{ Hand = "A4o", Action = "Check", Porcentajes =  75 },
                new Hands{ Hand = "K4o", Action = "Raise Over Limpers x3.4", Porcentajes =  32 },
                new Hands{ Hand = "K4o", Action = "Check", Porcentajes =  68 },
                new Hands{ Hand = "Q4o", Action = "Raise Over Limpers x3.4", Porcentajes =  20 },
                new Hands{ Hand = "Q4o", Action = "Check", Porcentajes =  80 },
                new Hands{ Hand = "J4o", Action = "Raise Over Limpers x3.4", Porcentajes =  22 },
                new Hands{ Hand = "J4o", Action = "Check", Porcentajes =  78 },
                new Hands{ Hand = "T4o", Action = "Raise Over Limpers x3.4", Porcentajes =  16 },
                new Hands{ Hand = "T4o", Action = "Check", Porcentajes =  84 },
                new Hands{ Hand = "74o", Action = "Raise Over Limpers x3.4", Porcentajes =  10 },
                new Hands{ Hand = "74o", Action = "Check", Porcentajes =  90 },
                new Hands{ Hand = "64o", Action = "Raise Over Limpers x3.4", Porcentajes =  20 },
                new Hands{ Hand = "64o", Action = "Check", Porcentajes =  80 },
                new Hands{ Hand = "54o", Action = "Raise Over Limpers x3.4", Porcentajes =  44 },
                new Hands{ Hand = "54o", Action = "Check", Porcentajes =  56 },
                new Hands{ Hand = "44", Action = "Raise Over Limpers x3.4", Porcentajes =  62 },
                new Hands{ Hand = "44", Action = "Check", Porcentajes =  38 },
                new Hands{ Hand = "43s", Action = "Raise Over Limpers x3.4", Porcentajes =  26 },
                new Hands{ Hand = "43s", Action = "Check", Porcentajes =  74 },
                new Hands{ Hand = "42s", Action = "Raise Over Limpers x3.4", Porcentajes =  78 },
                new Hands{ Hand = "42s", Action = "Check", Porcentajes =  22 },
                new Hands{ Hand = "A3o", Action = "Raise Over Limpers x3.4", Porcentajes =  39 },
                new Hands{ Hand = "A3o", Action = "Check", Porcentajes =  61 },
                new Hands{ Hand = "K3o", Action = "Raise Over Limpers x3.4", Porcentajes =  18 },
                new Hands{ Hand = "K3o", Action = "Check", Porcentajes =  82 },
                new Hands{ Hand = "Q3o", Action = "Raise Over Limpers x3.4", Porcentajes =  14 },
                new Hands{ Hand = "Q3o", Action = "Check", Porcentajes =  86 },
                new Hands{ Hand = "J3o", Action = "Raise Over Limpers x3.4", Porcentajes =  11 },
                new Hands{ Hand = "J3o", Action = "Check", Porcentajes =  89 },
                new Hands{ Hand = "T3o", Action = "Raise Over Limpers x3.4", Porcentajes =  37 },
                new Hands{ Hand = "T3o", Action = "Check", Porcentajes =  63 },
                new Hands{ Hand = "53o", Action = "Raise Over Limpers x3.4", Porcentajes =  32 },
                new Hands{ Hand = "53o", Action = "Check", Porcentajes =  68 },
                new Hands{ Hand = "43o", Action = "Raise Over Limpers x3.4", Porcentajes =  25 },
                new Hands{ Hand = "43o", Action = "Check", Porcentajes =  75 },
                new Hands{ Hand = "33", Action = "Raise Over Limpers x3.4", Porcentajes =  52 },
                new Hands{ Hand = "33", Action = "Check", Porcentajes =  48 },
                new Hands{ Hand = "32s", Action = "Raise Over Limpers x3.4", Porcentajes =  54 },
                new Hands{ Hand = "32s", Action = "Check", Porcentajes =  46 },
                new Hands{ Hand = "A2o", Action = "Raise Over Limpers x3.4", Porcentajes =  66 },
                new Hands{ Hand = "A2o", Action = "Check", Porcentajes =  34 },
                new Hands{ Hand = "K2o", Action = "Raise Over Limpers x3.4", Porcentajes =  28 },
                new Hands{ Hand = "K2o", Action = "Check", Porcentajes =  72 },
                new Hands{ Hand = "Q2o", Action = "Raise Over Limpers x3.4", Porcentajes =  21 },
                new Hands{ Hand = "Q2o", Action = "Check", Porcentajes =  79 },
                new Hands{ Hand = "J2o", Action = "Raise Over Limpers x3.4", Porcentajes =  30 },
                new Hands{ Hand = "J2o", Action = "Check", Porcentajes =  70 },
                new Hands{ Hand = "T2o", Action = "Raise Over Limpers x3.4", Porcentajes =  14 },
                new Hands{ Hand = "T2o", Action = "Check", Porcentajes =  86 },
                new Hands{ Hand = "22", Action = "Raise Over Limpers x3.4", Porcentajes =  54 },
                new Hands{ Hand = "22", Action = "Check", Porcentajes =  46 },
                new Hands{ Hand = "K8s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "K7s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "Q8s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "Q7s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "Q6s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "Q2s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "J8s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "J7s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "J6s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "J2s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "A8o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "83s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "72s", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "94o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "84o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "93o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "83o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "73o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "63o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "92o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "82o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "72o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "62o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "52o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "42o", Action = "Check", Porcentajes =  100 },
                new Hands{ Hand = "32o", Action = "Check", Porcentajes =  100 }
            };

            return ObtainActionHelper.ObtainAction(hands, hand);
        }
        public static string GetBigBlindvsSBCallAndRaise(string hand)
        {
            var hands = new List<Hands>
            {
                new Hands{ Hand = "A5s", Action = "All In", Porcentajes =  44 },
                new Hands{ Hand = "A5s", Action = "Call", Porcentajes =  56 },
                new Hands{ Hand = "A4s", Action = "All In", Porcentajes =  26 },
                new Hands{ Hand = "A4s", Action = "Raise x25.5", Porcentajes =  23 },
                new Hands{ Hand = "A4s", Action = "Call", Porcentajes =  51 },
                new Hands{ Hand = "AKo", Action = "All In", Porcentajes =  79 },
                new Hands{ Hand = "AKo", Action = "Raise x25.5", Porcentajes =  21 },
                new Hands{ Hand = "KQs", Action = "All In", Porcentajes =  19 },
                new Hands{ Hand = "KQs", Action = "Call", Porcentajes =  81 },
                new Hands{ Hand = "AQo", Action = "All In", Porcentajes =  55 },
                new Hands{ Hand = "AQo", Action = "Call", Porcentajes =  45 },
                new Hands{ Hand = "QJs", Action = "All In", Porcentajes =  39 },
                new Hands{ Hand = "QJs", Action = "Call", Porcentajes =  61 },
                new Hands{ Hand = "JJ", Action = "All In", Porcentajes =  47 },
                new Hands{ Hand = "JJ", Action = "Raise x25.5", Porcentajes =  45 },
                new Hands{ Hand = "JJ", Action = "Call", Porcentajes =  8 },
                new Hands{ Hand = "TT", Action = "All In", Porcentajes =  63 },
                new Hands{ Hand = "TT", Action = "Raise x25.5", Porcentajes =  2 },
                new Hands{ Hand = "TT", Action = "Call", Porcentajes =  35 },
                new Hands{ Hand = "99", Action = "All In", Porcentajes =  11 },
                new Hands{ Hand = "99", Action = "Raise x25.5", Porcentajes =  18 },
                new Hands{ Hand = "99", Action = "Call", Porcentajes =  71 },
                new Hands{ Hand = "66", Action = "All In", Porcentajes =  17 },
                new Hands{ Hand = "66", Action = "Raise x25.5", Porcentajes =  6 },
                new Hands{ Hand = "66", Action = "Marginal Call", Porcentajes =  66 },
                new Hands{ Hand = "66", Action = "Fold", Porcentajes =  11 },
                new Hands{ Hand = "AA", Action = "Raise x25.5", Porcentajes =  79 },
                new Hands{ Hand = "AA", Action = "Call", Porcentajes =  21 },
                new Hands{ Hand = "AKs", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "AQs", Action = "Raise x25.5", Porcentajes =  59 },
                new Hands{ Hand = "AQs", Action = "Call", Porcentajes =  41 },
                new Hands{ Hand = "A9s", Action = "Raise x25.5", Porcentajes =  34 },
                new Hands{ Hand = "A9s", Action = "Call", Porcentajes =  66 },
                new Hands{ Hand = "A8s", Action = "Raise x25.5", Porcentajes =  65 },
                new Hands{ Hand = "A8s", Action = "Call", Porcentajes =  35 },
                new Hands{ Hand = "A7s", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "A6s", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "A3s", Action = "Raise x25.5", Porcentajes =  31 },
                new Hands{ Hand = "A3s", Action = "Call", Porcentajes =  69 },
                new Hands{ Hand = "KK", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "K9s", Action = "Raise x25.5", Porcentajes =  51 },
                new Hands{ Hand = "K9s", Action = "Call", Porcentajes =  49 },
                new Hands{ Hand = "K5s", Action = "Raise x25.5", Porcentajes =  82 },
                new Hands{ Hand = "K5s", Action = "Fold", Porcentajes =  18 },
                new Hands{ Hand = "KQo", Action = "Raise x25.5", Porcentajes =  34 },
                new Hands{ Hand = "KQo", Action = "Call", Porcentajes =  66 },
                new Hands{ Hand = "QQ", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "QTs", Action = "Raise x25.5", Porcentajes =  12 },
                new Hands{ Hand = "QTs", Action = "Call", Porcentajes =  88 },
                new Hands{ Hand = "Q9s", Action = "Raise x25.5", Porcentajes =  100 },
                new Hands{ Hand = "AJo", Action = "Raise x25.5", Porcentajes =  43 },
                new Hands{ Hand = "AJo", Action = "Call", Porcentajes =  57 },
                new Hands{ Hand = "KJo", Action = "Raise x25.5", Porcentajes =  7 },
                new Hands{ Hand = "KJo", Action = "Marginal Call", Porcentajes =  24 },
                new Hands{ Hand = "KJo", Action = "Fold", Porcentajes =  69 },
                new Hands{ Hand = "ATo", Action = "Raise x25.5", Porcentajes =  40 },
                new Hands{ Hand = "ATo", Action = "Fold", Porcentajes =  60 },
                new Hands{ Hand = "KTo", Action = "Raise x25.5", Porcentajes =  28 },
                new Hands{ Hand = "KTo", Action = "Fold", Porcentajes =  72 },
                new Hands{ Hand = "T9s", Action = "Raise x25.5", Porcentajes =  1 },
                new Hands{ Hand = "T9s", Action = "Call", Porcentajes =  99 },
                new Hands{ Hand = "88", Action = "Raise x25.5", Porcentajes =  26 },
                new Hands{ Hand = "88", Action = "Call", Porcentajes =  74 },
                new Hands{ Hand = "77", Action = "Raise x25.5", Porcentajes =  17 },
                new Hands{ Hand = "77", Action = "Marginal Call", Porcentajes =  72 },
                new Hands{ Hand = "77", Action = "Fold", Porcentajes =  11 },
                new Hands{ Hand = "AJs", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "ATs", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "KJs", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "KTs", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "K6s", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "JTs", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "J9s", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "98s", Action = "Marginal Call", Porcentajes =  51 },
                new Hands{ Hand = "98s", Action = "Fold", Porcentajes =  49 },
                new Hands{ Hand = "87s", Action = "Marginal Call", Porcentajes =  53 },
                new Hands{ Hand = "87s", Action = "Fold", Porcentajes =  47 },
                new Hands{ Hand = "76s", Action = "Marginal Call", Porcentajes =  66 },
                new Hands{ Hand = "76s", Action = "Fold", Porcentajes =  34 },
                new Hands{ Hand = "65s", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "55", Action = "Marginal Call", Porcentajes =  38 },
                new Hands{ Hand = "55", Action = "Fold", Porcentajes =  62 },
                new Hands{ Hand = "54s", Action = "Call", Porcentajes =  100 },
                new Hands{ Hand = "44", Action = "Marginal Call", Porcentajes =  28 },
                new Hands{ Hand = "44", Action = "Fold", Porcentajes =  72 }
            };

            return ObtainActionHelper.ObtainAction(hands, hand);
        }

        #endregion

    }
}
