<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Marten" Version="7.33.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenScrape.Domain\OpenScrape.Domain.csproj" />
  </ItemGroup>

</Project>
